-- Active: 1665537141988@@containers-us-west-94.railway.app@6814@railway
USE railway;

-- SADASDASDASDASD
/*
  
  
  
  
  */
DROP TABLE IF EXISTS cursos;
DROP TABLE IF EXISTS profesores ;
CREATE TABLE profesores 
(
    ID VARCHAR(10) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50),
    EDAD INT 
);

CREATE TABLE cursos(
    
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_PROFESOR VARCHAR(10),
    NOMBRE VARCHAR(100) NOT NULL,
    HORAS INT,
    INDEX(ID_PROFESOR),
    FOREIGN KEY (ID_PROFESOR) REFERENCES profesores(ID)
    
);

-- TRUNCATE cursos;
-- TRUNCATE profesores; NO SE PUEDE PORQUE TIENE UNA REFERENCIA A OTRA TABLA

INSERT INTO profesores VALUES 
    ('ABC','Carlos','Gonzales',40),
    ('ZXY','Carlos','Gonzales',NULL),
    ('XZQ','Stefano','Miles',NULL),
    ('OPP','Brian','Gimenez',NULL);
  --  ('ZXZ',NULL,'Gonzales',NULL)
    
INSERT INTO cursos VALUES 
    (0,'ABC','CURSO FULLSTACK IMPRESIONANTE, EL MEJOR DE TODOS',120),
    (0,'ZXY','CURSO FRONTEND IMPRESIONANTE, EL MEJOR DE TODOS',120),
    (0,'XZQ','CURSO BACKEND IMPRESIONANTE, EL MEJOR DE TODOS ',120),
    (0,'OPP','CURSO ANALISIS DE DATOS IMPRESIONANTE, EL MEJOR DE TODOS',120),
    (0,'OPP','CURSO UX/UI IMPRESIONANTE, EL MEJOR DE TODOS',120)
    ;

DELETE FROM cursos WHERE ID_PROFESOR='OPP';
DELETE FROM profesores WHERE ID='OPP'